mysql:
  image: mysql
  volumes:
    - rails_test_data:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: password
    MYSQL_DATABASE: app_development
  ports:
    - "3306:3306"
  command: mysqld --character-set-server=utf8mb4

redis:
  image: redis
  ports:
    - "6379:6379"